#!/bin/sh

# This file is sourced by display managers before the X user session starts.

unset XDG_CURRENT_DESKTOP
export XDG_CURRENT_DESKTOP="GNOME"

export QT_QPA_PLATFORMTHEME="qt5ct" QT_AUTO_SCREEN_SCALE_FACTOR=0
