#!/bin/sh

# This file is sourced by display managers before the X user session starts.

if [ "$XDG_CURRENT_DESKTOP" == "i3" ]; then
  export XDG_CURRENT_DESKTOP="$XDG_CURRENT_DESKTOP:GNOME"
fi

unset QT_QPA_PLATFORMTHEME QT_AUTO_SCREEN_SCALE_FACTOR
export QT_QPA_PLATFORMTHEME="qt5ct" QT_AUTO_SCREEN_SCALE_FACTOR=0
